const colors = {
  light: {
    text: "#1C1C1E",
    tint: "#F8BCCD",
    background: "#F5F5F7",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#F8BCCD",
    primaryForeground: "#1C1C1E",
    secondary: "#F2F2F7",
    secondaryForeground: "#1C1C1E",
    muted: "#F2F2F7",
    mutedForeground: "#8E8E93",
    accent: "#FFE4EE",
    accentForeground: "#1C1C1E",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5EA",
    input: "#E5E5EA",
    confirmed: "#F8BCCD",
    confirmedText: "#8B4D5C",
    shipped: "#BFD8FF",
    shippedText: "#1A5FA8",
    delivered: "#B8F0D0",
    deliveredText: "#1A7A45",
    unpaid: "#FFD4D4",
    unpaidText: "#A83232",
    partial: "#FFE8C0",
    partialText: "#9C6B00",
    paid: "#B8F0D0",
    paidText: "#1A7A45",
    overdue: "#FFCDD2",
    overdueText: "#B71C1C",
  },
  radius: 12,
};

export default colors;
